name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # 前端构建
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install deps and build React app
      working-directory: ./client
      run: |
        npm install
        npm run build

    # 后端构建
    - name: Write appsettings.json
      run: echo '${{ secrets.APPSETTINGS_JSON }}' > ./API/appsettings.json

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'
    
    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish 
      run: |
        dotnet publish -c Release -o ./myApp

    # 部署到阿里云
    - name: Deploy to Aliyun ECS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USER }}
        key: ${{ secrets.ALIYUN_KEY }}
        port: 22
        source: "./myApp/*"
        target: "/www/wwwroot/myapp"

